### ISSUE TITLE
TODO workflow

### ISSUE THREAD

**Issue by ebouchut** [ebouchut/learn#2]
Decide on tools to use and set up a workflow.
## Tools
- [ ] QuickTask Vim Plugin: https://github.com/aaronbieber/vim-quicktask/blob/master/doc/quicktask.txt
- [ ] Vim Org-Mode: https://github.com/jceb/vim-orgmode
- [x] Personal Wiki for Vim: http://www.vim.org/scripts/script.php?script_id=2226
## Workflow

TODO
